# Generated by Django 5.2.1 on 2025-05-23 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0032_rawproductoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='conversion', max_length=50, verbose_name='출처')),
                ('reason', models.TextField(verbose_name='실패 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.rawproduct')),
            ],
            options={
                'verbose_name': '실패 로그',
                'verbose_name_plural': '3. 실패 로그',
            },
        ),
    ]
