# Generated by Django 5.2.1 on 2025-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionlog',
            name='retailer',
            field=models.CharField(default=1, max_length=100, verbose_name='거래처'),
            preserve_default=False,
        ),
    ]
