# Generated by Django 5.2.1 on 2025-06-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0002_conversionlog_retailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionlog',
            options={'verbose_name': '실패 로그', 'verbose_name_plural': '3. 가공 실패 로그'},
        ),
    ]
