# Generated by Django 5.2.3 on 2025-07-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0003_alter_conversionlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '서버 모니터링',
                'verbose_name_plural': '🖥️ 서버 모니터링 (실시간)',
                'managed': False,
            },
        ),
    ]
