# Generated by Django 5.2.3 on 2025-08-08 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableColumnSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='예: product_list, member_list, supplier_list', max_length=50, verbose_name='페이지명')),
                ('column_settings', models.JSONField(default=dict, help_text="{'external_product_id': {'visible': True, 'order': 1}, ...}", verbose_name='컬럼 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 테이블 컬럼 설정',
                'verbose_name_plural': '사용자 테이블 컬럼 설정',
                'unique_together': {('user', 'page_name')},
            },
        ),
    ]
