# Generated by Django 5.2.1 on 2025-05-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=100, verbose_name='거래처')),
                ('brand_name', models.CharField(help_text='[전체] 입력 시 모든 브랜드에 적용됨', max_length=100, verbose_name='브랜드명')),
                ('category1', models.CharField(choices=[('의류', '의류'), ('신발', '신발'), ('가방', '가방'), ('액세서리', '액세서리')], max_length=20, verbose_name='카테고리')),
                ('markup', models.FloatField(default=1.0, verbose_name='마크업율')),
            ],
        ),
    ]
