# Generated by Django 5.2.1 on 2025-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_fixedcountry_remove_countrysetting_country_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.FloatField(default=1450, verbose_name='환율')),
                ('shipping_fee', models.FloatField(default=0, verbose_name='배송비')),
                ('VAT', models.FloatField(default=1.1, verbose_name='부가세율')),
                ('margin_rate', models.FloatField(default=1.3, verbose_name='마진율')),
                ('extra_fee', models.IntegerField(default=0, verbose_name='추가금액')),
                ('apply_special_tax', models.BooleanField(default=False, verbose_name='개소세 적용')),
            ],
            options={
                'verbose_name': '계산식',
                'verbose_name_plural': '1. 계산식',
            },
        ),
        migrations.AlterModelOptions(
            name='brandsetting',
            options={'verbose_name': '브랜드정리', 'verbose_name_plural': '3. 브랜드정리'},
        ),
        migrations.AlterModelOptions(
            name='countrysetting',
            options={'verbose_name': '원산지정리', 'verbose_name_plural': '4. 원산지정리'},
        ),
        migrations.AlterModelOptions(
            name='fixedcountry',
            options={'verbose_name': 'FTA적용여부', 'verbose_name_plural': '5. FTA적용여부'},
        ),
        migrations.AlterModelOptions(
            name='retailer',
            options={'verbose_name': '거래처처정리', 'verbose_name_plural': '2. 거래처정리'},
        ),
    ]
