# Generated by Django 5.2.1 on 2025-05-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_globalpricingsetting_alter_brandsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpricingsetting',
            options={'verbose_name': '표준계산식', 'verbose_name_plural': '1. 표준계산식'},
        ),
    ]
