# Generated by Django 5.2.1 on 2025-05-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_globalpricingsetting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpricingsetting',
            options={},
        ),
        migrations.RemoveField(
            model_name='globalpricingsetting',
            name='apply_special_tax',
        ),
        migrations.AddField(
            model_name='globalpricingsetting',
            name='special_tax_rate',
            field=models.FloatField(default=0.0, verbose_name='개소세율 (예: 0.2)'),
        ),
        migrations.CreateModel(
            name='PriceFormulaRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(verbose_name='금액범위 최소')),
                ('max_price', models.IntegerField(verbose_name='금액범위 최대')),
                ('formula', models.TextField(help_text='예: 가격 * 0.05 + 10000', verbose_name='가격공식')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_ranges', to='pricing.globalpricingsetting')),
            ],
            options={
                'verbose_name': '표준계산식',
                'verbose_name_plural': '1. 표준계산식',
            },
        ),
    ]
