# Generated by Django 5.2.1 on 2025-05-16 07:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_globalpricingsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsetting',
            name='category1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('의류', '의류'), ('신발', '신발'), ('가방', '가방'), ('액세서리', '액세서리')], max_length=100, verbose_name='카테고리'),
        ),
    ]
