# Generated by Django 5.2.1 on 2025-05-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_alter_brandsetting_category1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpricingsetting',
            name='extra_fee',
        ),
        migrations.AlterField(
            model_name='globalpricingsetting',
            name='VAT',
            field=models.FloatField(default=1.1, verbose_name='부가세율(%)'),
        ),
        migrations.AlterField(
            model_name='globalpricingsetting',
            name='exchange_rate',
            field=models.FloatField(default=1450, verbose_name='환율(원화)'),
        ),
        migrations.AlterField(
            model_name='globalpricingsetting',
            name='margin_rate',
            field=models.FloatField(default=1.3, verbose_name='마진율(%)'),
        ),
        migrations.AlterField(
            model_name='globalpricingsetting',
            name='shipping_fee',
            field=models.FloatField(default=0, verbose_name='배송비(%)'),
        ),
        migrations.AlterField(
            model_name='globalpricingsetting',
            name='special_tax_rate',
            field=models.FloatField(default=0.0, verbose_name='개소세율(%)'),
        ),
    ]
