# Generated by Django 5.2.1 on 2025-05-20 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_brandsetting_retailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsetting',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.retailer', verbose_name='거래처'),
        ),
    ]
