# Generated by Django 5.2.1 on 2025-05-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_alter_retailer_options_retailer_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrysetting',
            options={'verbose_name': '원산지정리', 'verbose_name_plural': '5. 원산지정리'},
        ),
        migrations.AlterModelOptions(
            name='fixedcountry',
            options={'verbose_name': 'FTA적용여부', 'verbose_name_plural': '4. FTA적용여부'},
        ),
    ]
