# Generated by Django 5.2.1 on 2025-05-21 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_alter_countrysetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcountry',
            name='fta_applicable',
            field=models.BooleanField(default=False, verbose_name='FTA 적용 여부'),
        ),
        migrations.AlterField(
            model_name='fixedcountry',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='표준국가명'),
        ),
        migrations.CreateModel(
            name='CountryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=100, unique=True, verbose_name='원본국가명')),
                ('standard_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.fixedcountry', verbose_name='표준국가')),
            ],
        ),
        migrations.DeleteModel(
            name='CountrySetting',
        ),
    ]
