# Generated by Django 5.2.1 on 2025-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_alter_fixedcountry_fta_applicable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsetting',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시즌'),
        ),
    ]
