# Generated by Django 5.2.1 on 2025-05-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_brandsetting_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='order_api_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주문용 리테일러명'),
        ),
    ]
