# Generated by Django 5.2.1 on 2025-05-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_retailer_order_api_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='last_fetch_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수집 완료 시간'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='last_fetch_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수집 시작 시간'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='last_fetched_count',
            field=models.PositiveIntegerField(default=0, verbose_name='수집 상품 수'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='last_register_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='등록 완료 시간'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='last_registered_count',
            field=models.PositiveIntegerField(default=0, verbose_name='등록 상품 수'),
        ),
    ]
