# Generated by Django 5.2.1 on 2025-06-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_retailer_last_fetch_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
