# Generated by Django 5.2.1 on 2025-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_retailer_created_by_retailer_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='auto_schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='⏰ 자동 스케줄'),
        ),
    ]
