# Generated by Django 5.2.3 on 2025-07-17 01:32

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_retailer_auto_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsetting',
            options={'ordering': ['retailer', 'priority', 'brand_name'], 'verbose_name': '브랜드정리', 'verbose_name_plural': '3. 브랜드정리'},
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='season',
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('의류', '의류'), ('신발', '신발'), ('가방', '가방'), ('액세서리', '액세서리'), ('전체', '전체')], default=['전체'], help_text='적용할 카테고리를 선택하세요', max_length=100, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_brand_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='description',
            field=models.TextField(blank=True, help_text='이 설정에 대한 설명', null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='genders',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('남성', '남성'), ('여성', '여성'), ('키즈', '키즈'), ('라이프', '라이프'), ('전체', '전체')], default=['전체'], help_text='적용할 성별을 선택하세요', max_length=100, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='priority',
            field=models.IntegerField(default=1, help_text='1=최우선, 숫자가 클수록 후순위', verbose_name='우선순위'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='seasons',
            field=models.TextField(blank=True, help_text='시즌을 쉼표로 구분하여 입력 (예: FW25,SS25,CARRYOVER)', null=True, verbose_name='시즌'),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brandsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_brand_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brandsetting',
            name='brand_name',
            field=models.CharField(help_text="특정 브랜드명 또는 '전체', 'ETC'", max_length=100, verbose_name='브랜드명'),
        ),
    ]
