# Generated by Django 5.2.3 on 2025-07-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_alter_brandsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandsetting',
            unique_together={('retailer', 'brand_name', 'seasons', 'priority')},
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='brandsetting',
            name='markup',
        ),
        migrations.CreateModel(
            name='BrandMarkupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성'), ('키즈', '키즈'), ('라이프', '라이프'), ('전체', '전체')], max_length=10, verbose_name='성별')),
                ('category', models.CharField(choices=[('의류', '의류'), ('신발', '신발'), ('가방', '가방'), ('액세서리', '액세서리'), ('전체', '전체')], max_length=10, verbose_name='카테고리')),
                ('markup', models.FloatField(verbose_name='마크업율')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='pricing.brandsetting', verbose_name='브랜드 설정')),
            ],
            options={
                'verbose_name': '세부 마크업',
                'verbose_name_plural': '세부 마크업',
                'ordering': ['brand_setting', 'gender', 'category'],
                'unique_together': {('brand_setting', 'gender', 'category')},
            },
        ),
    ]
