# Generated by Django 5.2.3 on 2025-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0023_alter_brandsetting_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerSeasonSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_code', models.CharField(db_index=True, max_length=20)),
                ('seasons', models.TextField(help_text='comma-separated 시즌 목록')),
            ],
            options={
                'verbose_name': '거래처 시즌 요약',
                'verbose_name_plural': '거래처 시즌 요약',
            },
        ),
    ]
