# Generated by Django 5.2.3 on 2025-08-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0024_retailerseasonsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='회사주소'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='business_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='사업자번호'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처'),
        ),
    ]
