# Generated by Django 5.2.1 on 2025-06-09 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0018_retailer_last_fetch_finished_at_and_more'),
        ('shop', '0036_remove_product_calculated_price_krw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '미확인'), ('CONFIRMED', '확인됨'), ('SHIPPED', '출고됨'), ('FAILED', '오류')], default='PENDING', max_length=20, verbose_name='진행 상태')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='확인 일시')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem', verbose_name='주문 항목')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.retailer', verbose_name='거래처')),
            ],
            options={
                'verbose_name': '주문 확인',
                'verbose_name_plural': '1. 거래처 주문확인 목록',
            },
        ),
    ]
