# Generated by Django 5.2.1 on 2025-06-09 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreview',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderreview',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 변경시각'),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='마지막 변경자'),
        ),
    ]
