# Generated by Django 5.2.1 on 2025-06-09 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0002_remove_orderreview_updated_at_and_more'),
        ('pricing', '0018_retailer_last_fetch_finished_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={'verbose_name': '주문 확인', 'verbose_name_plural': '2. 거래처 주문확인 목록'},
        ),
        migrations.CreateModel(
            name='RetailerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.retailer', verbose_name='거래처')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '거래처 유저',
                'verbose_name_plural': '1. 거래처 유저',
            },
        ),
    ]
