# Generated by Django 5.2.1 on 2025-06-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0003_alter_orderreview_options_retaileruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING - 미확인'), ('CONFIRMED', 'CONFIRMED - 확인됨'), ('SHIPPED', 'SHIPPED - 출고됨'), ('FAILED', 'FAILED - 오류')], default='PENDING', max_length=20, verbose_name='진행 상태'),
        ),
    ]
