# Generated by Django 5.2.1 on 2025-06-13 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0004_alter_orderreview_status'),
        ('pricing', '0018_retailer_last_fetch_finished_at_and_more'),
        ('shop', '0037_product_description_rawproduct_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.retailer'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING - 미확인'), ('CONFIRMED', 'CONFIRMED - 확인됨'), ('SHIPPED', 'SHIPPED - 출고됨'), ('CANCELED', 'CANCELED - 주문취소')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
