# Generated by Django 5.2.1 on 2025-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0005_alter_orderreview_last_updated_at_and_more'),
        ('pricing', '0019_retailer_is_running'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retaileruser',
            name='retailer',
        ),
        migrations.AddField(
            model_name='retaileruser',
            name='retailers',
            field=models.ManyToManyField(to='pricing.retailer', verbose_name='거래처'),
        ),
    ]
