# Generated by Django 5.2.1 on 2025-06-23 02:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0006_remove_retaileruser_retailer_retaileruser_retailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
