# Generated by Django 5.2.1 on 2025-06-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderreview', '0007_orderreview_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderreview',
            name='created_at',
        ),
    ]
