"""
Django settings for mallapi project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7%82x^bvs7rez$v(56--szs4xqwcxuf&#f#u4l1dp(_)y4dsoz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['114.207.245.20', 'localhost', '127.0.0.1', 'linkplusx.cafe24.com']


LANGUAGE_CODE = 'ko-kr'  # 한국어 기본값

# 지원할 언어들
LANGUAGES = [
    ('ko', 'Korean'),
    ('en', 'English'),
    ('it', 'Italian'),
]

USE_I18N = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'shop.apps.ShopConfig',
    'pricing.apps.PricingConfig',
    'dictionary.apps.DictionaryConfig',
    'eventlog.apps.EventlogConfig',
    'orderreview.apps.OrderreviewConfig',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',           # ✅ 바로 여기!
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mallapi.urls'


LOCALE_PATHS = [
    Path(BASE_DIR) / "locale",
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ✅ 반드시 이 줄이 포함되어야 템플릿 인식 가능
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'mallapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# settings.py


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mallapi',
        'USER': 'postgres',
        'PASSWORD': 'milanese1!',   # 직접 설정한 비밀번호
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



try:
    from .settings_local import *
except ImportError:
    pass



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'


# 운영환경용 static 최종 복사본 위치
STATIC_ROOT = BASE_DIR / "staticfiles"  # 예: /root/staticfiles


# 개발 중 참조용 정적 폴더 (여기엔 소스 파일 넣기)
STATICFILES_DIRS = [
    BASE_DIR / "static",   # 예: /root/static
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#js 파일 버전 바꾸기
STATIC_VERSION = "20250620"