# Generated by Django 5.2.1 on 2025-05-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='상품명')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='재고수량')),
                ('status', models.CharField(choices=[('pending', '미등록'), ('active', '등록됨')], default='pending', max_length=10, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='주문 수량')),
                ('status', models.CharField(choices=[('success', '성공'), ('fail', '실패')], default='success', max_length=10, verbose_name='주문 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='상품')),
            ],
        ),
    ]
