# Generated by Django 5.2.1 on 2025-05-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '장바구니', 'verbose_name_plural': '2. 장바구니'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문내역', 'verbose_name_plural': '3. 주문내역'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품', 'verbose_name_plural': '1. 상품'},
        ),
    ]
