# Generated by Django 5.2.1 on 2025-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=100, verbose_name='거래처')),
                ('brand_name', models.CharField(help_text='브랜드 구분이 없을 경우 [전체]로 입력', max_length=100, verbose_name='브랜드명')),
                ('category1', models.CharField(choices=[('의류', '의류'), ('신발', '신발'), ('가방', '가방'), ('액세서리', '액세서리')], max_length=20, verbose_name='카테고리')),
                ('markup', models.FloatField(default=1.0, verbose_name='마크업율')),
            ],
            options={
                'verbose_name': '주문내역',
                'verbose_name_plural': '3. 주문내역',
            },
        ),
    ]
