# Generated by Django 5.2.1 on 2025-05-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option_name',
            field=models.CharField(max_length=100, verbose_name='옵션명'),
        ),
    ]
