# Generated by Django 5.2.1 on 2025-05-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cart_product_alter_cart_product_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.productoption', verbose_name='옵션'),
            preserve_default=False,
        ),
    ]
