# Generated by Django 5.2.1 on 2025-05-19 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_product_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_option',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.cart')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productoption')),
            ],
            options={
                'verbose_name': '장바구니',
                'verbose_name_plural': '2. 장바구니',
            },
        ),
    ]
