# Generated by Django 5.2.1 on 2025-05-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_options_remove_cart_product_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '장바구니', 'verbose_name_plural': '2. 장바구니'},
        ),
        migrations.AlterModelOptions(
            name='cartoption',
            options={},
        ),
    ]
