# Generated by Django 5.2.1 on 2025-05-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_calculated_price_krw'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='고유상품 ID'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='external_option_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='외부 옵션 ID'),
        ),
    ]
