# Generated by Django 5.2.1 on 2025-05-20 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_remove_globalpricingsetting_extra_fee_and_more'),
        ('shop', '0015_product_external_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='관리자 메모'),
        ),
        migrations.AddField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pricing.retailer', verbose_name='거래처'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('SENT', '전송됨'), ('COMPLETED', '완료'), ('FAILED', '전송실패')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='원화가')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productoption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
