# Generated by Django 5.2.1 on 2025-05-20 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_remove_globalpricingsetting_extra_fee_and_more'),
        ('shop', '0016_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsetting',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_brandsettings', to='pricing.retailer', verbose_name='거래처'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.retailer', verbose_name='부띠끄명'),
        ),
    ]
