# Generated by Django 5.2.1 on 2025-05-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_brandsetting_retailer_alter_product_retailer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsetting',
            options={},
        ),
    ]
