# Generated by Django 5.2.1 on 2025-05-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_brandsetting_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandSetting',
        ),
    ]
