# Generated by Django 5.2.1 on 2025-05-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_delete_brandsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailer',
            field=models.CharField(max_length=100, verbose_name='부띠끄명'),
        ),
    ]
