# Generated by Django 5.2.1 on 2025-05-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='원본 브랜드명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=100, verbose_name='표준 브랜드명'),
        ),
    ]
