# Generated by Django 5.2.1 on 2025-05-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='브랜드명'),
        ),
    ]
