# Generated by Django 5.2.1 on 2025-05-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.CharField(max_length=100, verbose_name='부띠끄명')),
                ('external_product_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='고유상품 ID')),
                ('raw_brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='원본 브랜드명')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='치환된 브랜드명')),
                ('product_name', models.CharField(max_length=255, verbose_name='상품명')),
                ('category1', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리1')),
                ('category2', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리2')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('price_org', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='원가')),
                ('price_supply', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='공급가')),
                ('calculated_price_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='원화가')),
                ('status', models.CharField(choices=[('pending', '미등록'), ('converted', '등록됨')], default='pending', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '상품원본',
                'verbose_name_plural': '1. 상품원본 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '장바구니', 'verbose_name_plural': '3. 장바구니'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문내역', 'verbose_name_plural': '4. 주문내역'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품', 'verbose_name_plural': '2. 가공상품'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최초 등록일'),
        ),
    ]
