# Generated by Django 5.2.1 on 2025-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rawproduct_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='색상명'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='소재'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='원산지'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='소비자가'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시즌'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
    ]
