# Generated by Django 5.2.1 on 2025-05-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_rawproduct_color_rawproduct_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawproduct',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='rawproduct',
            name='calculated_price_krw',
        ),
    ]
