# Generated by Django 5.2.1 on 2025-05-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_rawproduct_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='image_url_1',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 1'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='image_url_2',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 2'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='image_url_3',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='price_org',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='COST'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='price_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='판매가'),
        ),
    ]
