# Generated by Django 5.2.1 on 2025-05-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_rawproduct_image_url_rawproduct_image_url_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='image_url_4',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
    ]
