# Generated by Django 5.2.1 on 2025-05-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rawproduct_image_url_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_1',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_4',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
    ]
