# Generated by Django 5.2.1 on 2025-05-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_product_image_url_product_image_url_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_4',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='이미지 URL'),
        ),
    ]
