# Generated by Django 5.2.1 on 2025-05-22 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_remove_product_image_url_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_option_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='외부 옵션 ID')),
                ('option_name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('stock', models.IntegerField(default=0, verbose_name='재고 수량')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.rawproduct')),
            ],
            options={
                'verbose_name': '원본 옵션',
                'verbose_name_plural': '1-1. 원본 옵션 목록',
            },
        ),
    ]
