# Generated by Django 5.2.1 on 2025-05-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_rawproductoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='고유상품 ID'),
        ),
    ]
