# Generated by Django 5.2.1 on 2025-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_discount_rate_rawproduct_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='옵션 가격'),
        ),
        migrations.AddField(
            model_name='rawproductoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='옵션 가격'),
        ),
    ]
