# Generated by Django 5.2.1 on 2025-05-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_productoption_price_rawproductoption_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='calculated_price_krw',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_supply',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_org',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='COST'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='옵션 COST'),
        ),
    ]
