# Generated by Django 5.2.1 on 2025-06-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_remove_product_calculated_price_krw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
    ]
