# Generated by Django 5.2.1 on 2025-06-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_product_description_rawproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 등록일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수집일'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수정일'),
        ),
    ]
