# Generated by Django 5.2.1 on 2025-06-16 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_message',
            field=models.TextField(blank=True, null=True, verbose_name='주문 전송 메시지 (실패 사유 등)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(blank=True, choices=[('SENT', '전송 완료'), ('FAILED', '전송 실패')], max_length=10, null=True, verbose_name='주문 전송 상태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='최초 등록일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='수집일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='수정일'),
            preserve_default=False,
        ),
    ]
