# Generated by Django 5.2.1 on 2025-06-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_cart_created_at_cart_created_by_cart_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
