# Generated by Django 5.2.1 on 2025-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_remove_cart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='external_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\torder_number(날짜-고유번호-업체명)'),
        ),
    ]
