# Generated by Django 5.2.1 on 2025-06-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_orderitem_external_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', '미등록'), ('active', '등록됨'), ('soldout', '품절됨')], default='pending', max_length=10, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='status',
            field=models.CharField(choices=[('pending', '미등록'), ('converted', '등록됨'), ('soldout', '품절됨')], default='pending', max_length=10, verbose_name='상태'),
        ),
    ]
