# Generated by Django 5.2.1 on 2025-06-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_alter_product_status_alter_rawproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('SENT', '전송됨'), ('COMPLETED', '완료'), ('FAILED', '전송실패'), ('SOIDOUT', '품절취소')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
    ]
