# Generated by Django 5.2.1 on 2025-06-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('SENT', '전송됨'), ('COMPLETED', '완료'), ('FAILED', '전송실패'), ('SOLDOUT', '품절취소'), ('PARTIAL', '부분실패')], default='PENDING', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(blank=True, choices=[('SENT', '전송 완료'), ('FAILED', '전송 실패'), ('SOLDOUT', '품절 취소')], max_length=10, null=True, verbose_name='주문 전송 상태'),
        ),
    ]
