# Generated by Django 5.2.1 on 2025-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_alter_order_status_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='option_url',
            field=models.URLField(blank=True, null=True, verbose_name='옵션 링크'),
        ),
        migrations.AddField(
            model_name='rawproductoption',
            name='option_url',
            field=models.URLField(blank=True, null=True, verbose_name='옵션 링크'),
        ),
    ]
