# Generated by Django 5.2.1 on 2025-06-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_productoption_option_url_rawproductoption_option_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoption',
            name='order_message',
            field=models.TextField(blank=True, null=True, verbose_name='전송 메시지'),
        ),
        migrations.AddField(
            model_name='cartoption',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PENDING', '대기중'), ('SENT', '전송완료'), ('FAILED', '전송실패')], default='PENDING', max_length=20, null=True, verbose_name='전송상태'),
        ),
    ]
