# Generated by Django 5.2.1 on 2025-06-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_cartoption_order_message_cartoption_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoption',
            name='last_sent_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
