# Generated by Django 5.2.1 on 2025-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_cartoption_last_sent_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='image_url_1',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 1'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='image_url_2',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 2'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='image_url_3',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='image_url_4',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
    ]
