# Generated by Django 5.2.3 on 2025-07-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_alter_product_image_url_alter_rawproduct_image_url_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='option_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='COST'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='image_url_4',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 4'),
        ),
    ]
