# Generated by Django 5.2.3 on 2025-07-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_orderitem_price_org_alter_orderitem_option_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='markup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='마크업'),
        ),
    ]
