# Generated by Django 5.2.3 on 2025-07-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_orderitem_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='공급가'),
        ),
    ]
