# Generated by Django 5.2.3 on 2025-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_orderitem_price_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markup',
            field=models.FloatField(blank=True, null=True, verbose_name='마크업'),
        ),
    ]
