# Generated by Django 5.2.3 on 2025-07-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_product_markup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calculated_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='원화가'),
        ),
    ]
