# Generated by Django 5.2.3 on 2025-07-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_product_calculated_price_krw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_1',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_4',
            field=models.CharField(blank=True, null=True, verbose_name='이미지 URL 4'),
        ),
    ]
