# Generated by Django 5.2.3 on 2025-08-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_remove_product_image_url_product_image_url_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='특정 리테일러용 수동 입력 가격 (자동 계산 무시하고 이 값 사용)', max_digits=12, null=True, verbose_name='수동 원화가'),
        ),
    ]
