# Generated by Django 5.2.3 on 2025-08-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_product_manual_price_krw'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_retail_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='특정 리테일러의 소비자가 수동 입력 시 사용', max_digits=12, null=True, verbose_name='소비자가 수동입력'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='자동 계산된 소비자가 (COST * 환율 * 1.22)', max_digits=12, null=True, verbose_name='자동 계산된 소비자가'),
        ),
    ]
