# Generated by Django 5.2.3 on 2025-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_product_manual_retail_price_krw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='manual_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='옵션 원화가 수동 입력 (자동계산 제외)', max_digits=12, null=True, verbose_name='수동 입력 판매가'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='옵션 자동 계산 원화가', max_digits=12, null=True, verbose_name='자동 계산 판매가'),
        ),
    ]
