# Generated by Django 5.2.3 on 2025-08-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_productoption_manual_price_krw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='공급가'),
        ),
    ]
