# Generated by Django 5.2.3 on 2025-08-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_product_price_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calculated_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='※입력금지※자동 계산된 원화가', max_digits=12, null=True, verbose_name='원화가'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='소비자가(euro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='공급가(euro)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price_krw',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='※입력금지※자동 계산된 소비자가 (COST * 환율 * 1.22)', max_digits=12, null=True, verbose_name='소비자가'),
        ),
    ]
