# Generated by Django 5.2.3 on 2025-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_alter_product_calculated_price_krw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='고유상품 ID'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['retailer', 'external_product_id'], name='ix_prod_retailer_extid'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('retailer', 'external_product_id'), name='uq_prod_retailer_extid'),
        ),
    ]
