# Generated by Django 5.2.3 on 2025-08-04 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='쿠폰코드')),
                ('name', models.CharField(max_length=100, verbose_name='쿠폰 이름')),
                ('discount_type', models.CharField(choices=[('percent', '퍼센트 할인'), ('amount', '정액 할인')], max_length=10)),
                ('discount_value', models.PositiveIntegerField(verbose_name='할인 수치')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='최소 주문금액')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일')),
                ('valid_to', models.DateTimeField(verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 가능 여부')),
            ],
        ),
    ]
