# Generated by Django 5.2.3 on 2025-09-02 06:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_member_grade_fixed_member_grade_fixed_at_and_more'),
        ('promotion', '0002_delete_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이벤트명')),
                ('description', models.TextField(blank=True, verbose_name='이벤트 설명')),
                ('discount_type', models.CharField(choices=[('fixed', '정액할인'), ('percent', '정률할인')], default='percent', max_length=10, verbose_name='할인 타입')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='할인 값')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='최대 할인 금액')),
                ('target_all_products', models.BooleanField(default=True, verbose_name='전체 상품 적용')),
                ('target_categories', models.JSONField(blank=True, default=list, help_text='특정 카테고리만 적용할 경우', verbose_name='대상 카테고리')),
                ('target_brands', models.JSONField(blank=True, default=list, help_text='특정 브랜드만 적용할 경우', verbose_name='대상 브랜드')),
                ('start_date', models.DateTimeField(verbose_name='시작일시')),
                ('end_date', models.DateTimeField(verbose_name='종료일시')),
                ('min_purchase_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='최소 구매금액')),
                ('priority', models.IntegerField(default=100, help_text='낮은 숫자가 높은 우선순위', verbose_name='우선순위')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '이벤트 할인',
                'verbose_name_plural': '이벤트 할인',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 기본 할인 규칙', max_length=100, verbose_name='규칙명')),
                ('priority_order', models.CharField(choices=[('grade_first', '등급할인 → 쿠폰 → 이벤트'), ('coupon_first', '쿠폰 → 등급할인 → 이벤트'), ('best_discount', '가장 유리한 할인 자동선택')], default='grade_first', max_length=20, verbose_name='할인 적용 순서')),
                ('allow_coupon_stack', models.BooleanField(default=False, help_text='여러 쿠폰 동시 사용 가능 여부', verbose_name='쿠폰 중복사용 허용')),
                ('allow_grade_coupon_stack', models.BooleanField(default=True, help_text='등급할인과 쿠폰할인 동시 적용 가능', verbose_name='등급할인+쿠폰 중복 허용')),
                ('max_discount_rate', models.DecimalField(decimal_places=2, default=50.0, help_text='전체 할인의 최대 한도', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='최대 할인율(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '프로모션 규칙',
                'verbose_name_plural': '프로모션 규칙',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='관리자용 쿠폰 이름', max_length=100, verbose_name='쿠폰명')),
                ('code', models.CharField(help_text='사용자가 입력할 쿠폰 코드', max_length=50, unique=True, verbose_name='쿠폰 코드')),
                ('description', models.TextField(blank=True, help_text='쿠폰에 대한 상세 설명', verbose_name='설명')),
                ('discount_type', models.CharField(choices=[('fixed', '정액할인'), ('percent', '정률할인')], default='fixed', max_length=10, verbose_name='할인 타입')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='정액할인: 원 단위, 정률할인: % 단위', max_digits=12, verbose_name='할인 값')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=0, help_text='정률할인 시 최대 할인 한도 (원)', max_digits=12, null=True, verbose_name='최대 할인 금액')),
                ('min_purchase_amount', models.DecimalField(decimal_places=0, default=0, help_text='쿠폰 사용을 위한 최소 주문 금액', max_digits=12, verbose_name='최소 구매금액')),
                ('usage_limit', models.IntegerField(blank=True, help_text='전체 사용 가능 횟수 (미입력시 무제한)', null=True, verbose_name='총 사용 제한')),
                ('usage_limit_per_user', models.IntegerField(default=1, help_text='한 회원이 사용할 수 있는 최대 횟수', verbose_name='회원별 사용 제한')),
                ('start_date', models.DateTimeField(help_text='쿠폰 사용 가능 시작 시간', verbose_name='시작일시')),
                ('end_date', models.DateTimeField(help_text='쿠폰 사용 만료 시간', verbose_name='종료일시')),
                ('target_member_types', models.CharField(choices=[('all', '모든 회원'), ('B2C', 'B2C 회원만'), ('B2B', 'B2B 회원만')], default='all', max_length=20, verbose_name='대상 회원')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('used_count', models.IntegerField(default=0, help_text='자동 계산되는 총 사용 횟수', verbose_name='사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('target_grades', models.ManyToManyField(blank=True, help_text='특정 등급만 사용 가능 (미선택시 모든 등급)', to='members.membergrade', verbose_name='대상 등급')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='향후 주문 시스템 연동용', max_length=100, null=True, verbose_name='주문번호')),
                ('original_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='원래 금액')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='할인 금액')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='최종 금액')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='사용일시')),
                ('status', models.CharField(choices=[('used', '사용됨'), ('cancelled', '취소됨')], default='used', max_length=20, verbose_name='상태')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotion.coupon', verbose_name='쿠폰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '쿠폰 사용내역',
                'verbose_name_plural': '쿠폰 사용내역',
                'ordering': ['-used_at'],
            },
        ),
    ]
