# Generated by Django 5.2.1 on 2025-05-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='표준 브랜드명')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_category', models.CharField(max_length=100, verbose_name='원본 카테고리')),
                ('standard_category', models.CharField(max_length=100, verbose_name='치환 카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='금칙어')),
            ],
        ),
        migrations.CreateModel(
            name='BrandAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='치환 브랜드명')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dictionary.brand', verbose_name='표준 브랜드')),
            ],
        ),
    ]
