# Generated by Django 5.2.1 on 2025-05-20 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(max_length=100, verbose_name='대분류')),
                ('level_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='중분류')),
                ('level_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='소분류')),
                ('level_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='소소분류')),
            ],
            options={
                'verbose_name': '표준 카테고리',
                'verbose_name_plural': '2. 표준 카테고리',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryalias',
            options={'verbose_name': '카테고리 매핑', 'verbose_name_plural': '3. 카테고리 매핑'},
        ),
        migrations.RemoveField(
            model_name='categoryalias',
            name='raw_category',
        ),
        migrations.AddField(
            model_name='categoryalias',
            name='raw_name',
            field=models.CharField(default=1, max_length=100, verbose_name='원본 카테고리명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryalias',
            name='standard_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.category', verbose_name='표준 카테고리'),
        ),
    ]
