# Generated by Django 5.2.1 on 2025-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_category_alter_categoryalias_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=100, unique=True, verbose_name='원본 대분류')),
                ('normalized_name', models.CharField(max_length=100, verbose_name='표준 대분류')),
            ],
            options={
                'verbose_name': '대분류 매핑',
                'verbose_name_plural': '1. 대분류 매핑',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=100, unique=True, verbose_name='원본 중분류')),
                ('normalized_name', models.CharField(max_length=100, verbose_name='표준 중분류')),
            ],
            options={
                'verbose_name': '중분류 매핑',
                'verbose_name_plural': '2. 중분류 매핑',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=100, unique=True, verbose_name='원본 소분류')),
                ('normalized_name', models.CharField(max_length=100, verbose_name='표준 소분류')),
            ],
            options={
                'verbose_name': '소분류 매핑',
                'verbose_name_plural': '3. 소분류 매핑',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=100, unique=True, verbose_name='원본 소소분류')),
                ('normalized_name', models.CharField(max_length=100, verbose_name='표준 소소분류')),
            ],
            options={
                'verbose_name': '소소분류 매핑',
                'verbose_name_plural': '4. 소소분류 매핑',
            },
        ),
        migrations.AlterField(
            model_name='categoryalias',
            name='standard_category',
            field=models.CharField(max_length=100, verbose_name='치환 카테고리'),
        ),
        migrations.AlterModelOptions(
            name='categoryalias',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoryalias',
            name='raw_name',
        ),
        migrations.AddField(
            model_name='categoryalias',
            name='raw_category',
            field=models.CharField(default=1, max_length=100, verbose_name='원본 카테고리'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
