# Generated by Django 5.2.1 on 2025-05-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_categorylevel1_categorylevel2_categorylevel3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel1Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='치환 대분류')),
            ],
            options={
                'verbose_name': '대분류카테고리',
                'verbose_name_plural': '1.대분류카테고리',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel2Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='치환 중분류')),
            ],
            options={
                'verbose_name': '중분류카테고리',
                'verbose_name_plural': '2. 중분류카테고리리',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel3Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='치환 소분류')),
            ],
            options={
                'verbose_name': '소분류',
                'verbose_name_plural': '3. 소분류',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel4Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='치환 소소분류')),
            ],
            options={
                'verbose_name': '소소분류',
                'verbose_name_plural': '4. 소소분류',
            },
        ),
        migrations.DeleteModel(
            name='CategoryAlias',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '브랜드매핑', 'verbose_name_plural': 'A. 브랜드매핑'},
        ),
        migrations.AlterModelOptions(
            name='categorylevel1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorylevel2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorylevel3',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorylevel4',
            options={},
        ),
        migrations.RemoveField(
            model_name='categorylevel1',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel1',
            name='raw_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel2',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel2',
            name='raw_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel3',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel3',
            name='raw_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel4',
            name='normalized_name',
        ),
        migrations.RemoveField(
            model_name='categorylevel4',
            name='raw_name',
        ),
        migrations.AddField(
            model_name='categorylevel1',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='표준 대분류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorylevel2',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='표준 중분류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorylevel3',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='표준 소분류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorylevel4',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='표준 소소분류'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorylevel1alias',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dictionary.categorylevel1'),
        ),
        migrations.AddField(
            model_name='categorylevel2alias',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dictionary.categorylevel2'),
        ),
        migrations.AddField(
            model_name='categorylevel3alias',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dictionary.categorylevel3'),
        ),
        migrations.AddField(
            model_name='categorylevel4alias',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='dictionary.categorylevel4'),
        ),
    ]
