# Generated by Django 5.2.1 on 2025-05-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_categorylevel1alias_categorylevel2alias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylevel1',
            options={'verbose_name': '대분류카테고리', 'verbose_name_plural': '1. 대분류'},
        ),
        migrations.AlterModelOptions(
            name='categorylevel1alias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorylevel2',
            options={'verbose_name': '중분류카테고리', 'verbose_name_plural': '2. 중분류'},
        ),
        migrations.AlterModelOptions(
            name='categorylevel2alias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorylevel3',
            options={'verbose_name': '소분류', 'verbose_name_plural': '3. 소분류'},
        ),
        migrations.AlterModelOptions(
            name='categorylevel3alias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorylevel4',
            options={'verbose_name': '소소분류', 'verbose_name_plural': '4. 소소분류'},
        ),
        migrations.AlterModelOptions(
            name='categorylevel4alias',
            options={},
        ),
    ]
