# Generated by Django 5.2.3 on 2025-08-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_categorylevel1_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='서비스 노출'),
        ),
    ]
