# Generated by Django 5.2.3 on 2025-07-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('member_type', models.CharField(choices=[('B2C', '일반회원'), ('B2B', '사업자회원')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('marketing_agree', models.BooleanField(default=False)),
                ('point', models.PositiveIntegerField(default=0)),
                ('recommender_id', models.CharField(blank=True, max_length=30, null=True)),
                ('join_channel', models.CharField(default='direct', max_length=20)),
                ('is_forever_member', models.BooleanField(default=False, verbose_name='평생회원 여부')),
                ('is_sms_agree', models.BooleanField(default=True, verbose_name='SMS 수신 동의')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='불량회원 여부')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='운영 메모')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_number', models.CharField(blank=True, max_length=50, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('business_item', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
