# Generated by Django 5.2.3 on 2025-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_restore',
            field=models.BooleanField(default=True, help_text='False면 복구할 수 없는 삭제입니다.', verbose_name='복구 가능 여부'),
        ),
        migrations.AddField(
            model_name='member',
            name='delete_reason',
            field=models.CharField(blank=True, help_text='관리자가 입력한 삭제 사유입니다.', max_length=500, verbose_name='삭제 사유'),
        ),
        migrations.AddField(
            model_name='member',
            name='delete_type',
            field=models.CharField(blank=True, choices=[('admin_delete', '관리자 삭제'), ('self_withdrawal', '회원 탈퇴'), ('auto_cleanup', '자동 정리'), ('policy_violation', '정책 위반')], help_text='삭제가 발생한 경위를 구분합니다.', max_length=20, verbose_name='삭제 유형'),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='실제 삭제가 실행된 시간입니다.', null=True, verbose_name='삭제 일시'),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_by',
            field=models.CharField(blank=True, help_text='삭제를 실행한 관리자 아이디나 시스템명입니다.', max_length=100, verbose_name='삭제 실행자'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='True면 삭제된 회원으로 처리됩니다.', verbose_name='삭제 여부'),
        ),
        migrations.AddField(
            model_name='member',
            name='restore_deadline',
            field=models.DateTimeField(blank=True, help_text='이 날짜 이후에는 자동으로 완전삭제됩니다.', null=True, verbose_name='복구 가능 기한'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_deleted', 'created_at'], name='members_mem_is_dele_842ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['deleted_at'], name='members_mem_deleted_17d12a_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['restore_deadline'], name='members_mem_restore_7dfbe0_idx'),
        ),
    ]
