# Generated by Django 5.2.3 on 2025-08-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_can_restore_member_delete_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(help_text='변경을 실행한 관리자 아이디 또는 시스템명', max_length=100, verbose_name='변경자')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('change_type', models.CharField(choices=[('create', '계정 생성'), ('update', '정보 수정'), ('status_change', '상태 변경'), ('point_adjust', '포인트 조정'), ('password_reset', '비밀번호 재설정'), ('admin_memo', '관리자 메모'), ('delete', '계정 삭제'), ('restore', '계정 복구')], max_length=20, verbose_name='변경 유형')),
                ('field_name', models.CharField(blank=True, help_text='변경된 필드명 (예: email, phone, is_active)', max_length=100, verbose_name='변경 필드')),
                ('old_value', models.TextField(blank=True, verbose_name='이전 값')),
                ('new_value', models.TextField(blank=True, verbose_name='새 값')),
                ('description', models.CharField(blank=True, help_text='변경 사유나 추가 설명', max_length=500, verbose_name='변경 설명')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='사용자 에이전트')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='members.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 변경 로그',
                'verbose_name_plural': '회원 변경 로그',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['member', '-changed_at'], name='members_mem_member__6a3a7e_idx'), models.Index(fields=['changed_by', '-changed_at'], name='members_mem_changed_c336dc_idx'), models.Index(fields=['change_type', '-changed_at'], name='members_mem_change__249ebe_idx')],
            },
        ),
    ]
