# Generated by Django 5.2.3 on 2025-08-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberchangelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberChangeLog',
        ),
    ]
