# Generated by Django 5.2.3 on 2025-08-28 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_memberchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade_fixed',
            field=models.BooleanField(default=False, help_text='체크 시 자동 승급/강등 방지', verbose_name='등급 고정'),
        ),
        migrations.AddField(
            model_name='member',
            name='grade_fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='등급 고정 일시'),
        ),
        migrations.AddField(
            model_name='member',
            name='grade_fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_grade_members', to=settings.AUTH_USER_MODEL, verbose_name='등급 고정한 관리자'),
        ),
        migrations.AddField(
            model_name='member',
            name='grade_fixed_reason',
            field=models.TextField(blank=True, help_text='등급을 고정한 상세 사유', verbose_name='등급 고정 사유'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_order_date',
            field=models.DateField(blank=True, help_text='마지막 주문 날짜', null=True, verbose_name='최근 주문일'),
        ),
        migrations.AddField(
            model_name='member',
            name='total_orders',
            field=models.IntegerField(default=0, help_text='총 주문 횟수 (자동 계산)', verbose_name='총 주문수'),
        ),
        migrations.AddField(
            model_name='member',
            name='total_spent',
            field=models.DecimalField(decimal_places=0, default=0, help_text='총 구매 금액 (자동 계산)', max_digits=12, verbose_name='총 구매금액'),
        ),
        migrations.CreateModel(
            name='MemberGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 브론즈, 실버, 골드, VIP', max_length=50, verbose_name='등급명')),
                ('display_name', models.CharField(blank=True, help_text='화면에 표시될 등급명', max_length=50, verbose_name='표시명')),
                ('member_type', models.CharField(choices=[('B2C', '일반회원'), ('B2B', '사업자회원'), ('ALL', '공통')], default='ALL', max_length=10, verbose_name='적용 회원타입')),
                ('order', models.IntegerField(default=999, help_text='낮은 숫자일수록 높은 등급 (1=최고등급)', verbose_name='등급 순서')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, help_text='등급별 기본 할인율', max_digits=5, verbose_name='할인율 (%)')),
                ('point_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='구매금액 대비 포인트 적립 비율', max_digits=5, verbose_name='포인트 적립율 (%)')),
                ('auto_upgrade', models.BooleanField(default=True, help_text='조건 달성 시 자동으로 등급 승급', verbose_name='자동 승급 사용')),
                ('min_order_count', models.IntegerField(blank=True, help_text='승급을 위한 최소 주문 횟수', null=True, verbose_name='최소 주문횟수')),
                ('min_total_amount', models.DecimalField(blank=True, decimal_places=0, help_text='승급을 위한 최소 총 구매금액 (원)', max_digits=12, null=True, verbose_name='최소 총 구매금액')),
                ('min_period_amount', models.DecimalField(blank=True, decimal_places=0, help_text='1년간 최소 구매금액 (원)', max_digits=12, null=True, verbose_name='기간별 구매금액')),
                ('is_default', models.BooleanField(default=False, help_text='신규 가입시 자동 할당되는 등급', verbose_name='기본 등급')),
                ('color_code', models.CharField(default='#6c757d', help_text='등급 표시용 색상 코드 (예: #ff6b6b)', max_length=7, verbose_name='등급 색상')),
                ('icon_class', models.CharField(default='fas fa-user', help_text='FontAwesome 아이콘 클래스', max_length=50, verbose_name='아이콘 클래스')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '회원 등급',
                'verbose_name_plural': '회원 등급',
                'ordering': ['member_type', 'order', 'name'],
                'unique_together': {('member_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='현재 회원 등급', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membergrade', verbose_name='회원 등급'),
        ),
        migrations.CreateModel(
            name='MemberGradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.CharField(choices=[('auto', '자동 승급'), ('manual', '수동 변경'), ('signup', '신규 가입'), ('promotion', '특별 승급'), ('demotion', '등급 강등'), ('fixed', '등급 고정'), ('unfixed', '고정 해제')], default='manual', max_length=20, verbose_name='변경 사유')),
                ('reason_detail', models.TextField(blank=True, help_text='등급 변경에 대한 상세한 설명', verbose_name='상세 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경일시')),
                ('changed_by', models.ForeignKey(blank=True, help_text='관리자가 수동 변경한 경우', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_histories', to='members.member', verbose_name='회원')),
                ('new_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_grade_histories', to='members.membergrade', verbose_name='새 등급')),
                ('old_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_grade_histories', to='members.membergrade', verbose_name='이전 등급')),
            ],
            options={
                'verbose_name': '등급 변경 이력',
                'verbose_name_plural': '등급 변경 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
