# Generated by Django 5.2.3 on 2025-08-05 03:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='쇼핑몰 이름')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='로고')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='대표 이메일')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='대표 전화번호')),
                ('business_hours', models.CharField(blank=True, max_length=255, verbose_name='운영 시간')),
                ('footer_text', models.TextField(blank=True, verbose_name='푸터 문구')),
                ('terms_of_service', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='이용약관')),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='개인정보처리방침')),
                ('ecommerce_notice', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='전자상거래법 고지사항')),
                ('return_policy', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='청약철회/환불정책')),
            ],
        ),
    ]
