# Generated by Django 5.2.3 on 2025-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='사업장 주소'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/license/', verbose_name='사업자등록증 이미지'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='사업자등록번호'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='대표자명'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='commerce_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='통신판매업 신고번호'),
        ),
    ]
