# Generated by Django 5.2.3 on 2025-08-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall_settings', '0003_operatorprofile'),
        ('pricing', '0025_retailer_address_retailer_business_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='allowed_retailers',
            field=models.ManyToManyField(blank=True, to='pricing.retailer'),
        ),
    ]
