# Generated by Django 5.2.3 on 2025-08-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall_settings', '0004_operatorprofile_allowed_retailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='연락처'),
        ),
    ]
